language: python
python:
  - "2.7"
  - "3.5"
  - "pypy"
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - py.test ec2_route53_sync/utils --cov=ec2_route53_sync/utils --doctest-modules
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.5" ]];
    then
      coveralls;
    fi

